parser: "@typescript-eslint/parser"
env:
  mocha: true
  truffle/globals: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  project: tsconfig.json
plugins:
  - "@typescript-eslint"
  - "truffle"
root: true
rules:
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
      varsIgnorePattern: _
